### ISSUE TITLE
Paper Mario Color Splash Collision Saving Issues

### ISSUE THREAD

**Issue by ghost** [KillzXGaming/CollisionSceneBinary#1]
Issue #1

When opening an existing .csb for Color Splash, or importing a .dae, saving the collision afterwards (edited or unedited) saves in the compressed .zstd format. Color Splash doesn't use ZSTD compression, so these need to be left uncompressed as they need to be added into a .lzarc, or have the option to be compressed with LZ77 Wii Type 11.

Issue #2

When saving the file with zstd compression anyway, and decompressing it with Switch Toolbox and then packing the files into the Lzarc with the lzarc tool, the collision crashes regardless on if its an original .csb opened and then saved, or a .dae model imported and the .csb and .ctb saved with or without editing the collision type and flags.

**Comment by KillzXGaming** [comment]
Fixed along with other various save issues related to color splash
